### ISSUE TITLE
[1.10.2] Spam on server console

### ISSUE THREAD

**Issue by kwpugh** [RootsTeam/Roots#101]
Forge: 2056
Mod: roots-1.10.2-0.110.0.jar

Message:

[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]: java.lang.NoSuchMethodException: elucent.roots.entity.EntityAccelerator.<init>(net.minecraft.world.World)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at java.lang.Class.getConstructor0(Class.java:3082)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at java.lang.Class.getConstructor(Class.java:1825)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.doSpawn(TileInvisMobSpawner.java:94)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner.func_73660_a(TileInvisMobSpawner.java:58)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.world.World.func_72939_s(World.java:1802)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[17:36:35] [Server thread/INFO] [STDERR]: [se.Matryoshika.Underworld.Content.TileEntity.TileInvisMobSpawner:doSpawn:111]:       at java.lang.Thread.run(Thread.java:745)

**Comment by Matryoshika** [comment]
Issue was caused on Underworld's side. Already been fixed.
Custom entity instantiation from classes. Catch'd due to different constructor. Now simply ignored.
https://github.com/Matryoshika/Underworld/commit/cfb2f7a59f5425f6d112ff3e9e639766267e71e0

**Comment by elucent** [comment]
If this is fixed, I'll close this issue. If not, just let me know and I can add some blank constructors.
