### ISSUE TITLE
Disconnect from server when using Regen Staff

### ISSUE THREAD

**Issue by Brunhine** [RootsTeam/Roots#102]
> Forge Mod Loader version 12.18.1.2050 for Minecraft 1.10.2
> roots version 1.10.2-0.110.0

When activating regen staff, player is disconnected from server, but game does not crash.

appears to be issue with call to `player.setVelocity(0, 0, 0);`  in `ComponentPeony.castingAction()` (line 62)

Stack trace follows:

`
[02:35:12] [Server thread/WARN]: Failed to handle packet for /XX.XXX.XXX.X:XXXXX
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_70016_h(DDD)V
	at elucent.roots.component.components.ComponentPeony.castingAction(ComponentPeony.java:62) ~[ComponentPeony.class:?]
	at elucent.roots.item.ItemStaff.onUsingTick(ItemStaff.java:169) ~[ItemStaff.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2503) ~[sf.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1940) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more
`

**Comment by elucent** [comment]
Should be fixed, I just removed the setVelocity line since I don't think it's very necessary.
