### ISSUE TITLE
Staff spells not firing on server... not sure why

### ISSUE THREAD

**Issue by Gorgok** [RootsTeam/Roots#112]
Running a server with forge 1.10.2 12.18.1.2075 with roots 0.112.0 and whenever i try to casts a spell on the server the effect does not fire, and instead the below appears on the console. Taking the same world on the same mods to single player makes the same items work. The only mods the server runs that my client does not are Aroma1997Core, AromaBackup, and Dynmap-2.3-forge. 

`[02:45:49] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149751_l(Lnet/minecraft/block/state/IBlockState;)Z
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149751_l(Lnet/minecraft/block/state/IBlockState;)Z
	at elucent.roots.Util.getRayTrace(Util.java:101) ~[Util.class:?]
	at elucent.roots.component.components.ComponentPoisonousPotato.doEffect(ComponentPoisonousPotato.java:46) ~[ComponentPoisonousPotato.class:?]
	at elucent.roots.item.ItemStaff.func_77615_a(ItemStaff.java:108) ~[ItemStaff.class:?]
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:459) ~[adz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184597_cx(EntityLivingBase.java:2648) ~[sf.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:597) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more`

**Comment by elucent** [comment]
Fixed for the next version, which is coming in the next few days.
