### ISSUE TITLE
Can't Load My New World

### ISSUE THREAD

**Issue by kenijey** [RootsTeam/Roots#194]
after the update (roots-2-0.012.jar) i can't load my world. and i tried creating a new world, it says "**A fatal error has occurred, this connection is terminated**". here is the fml log part which tells me roots mod problems
`[19:34:59] [Server thread/INFO] [jsonrecipeedit/]: Player kenijey Joined in dim 0
[19:35:00] [Netty Local Client IO #1/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at teamroots.roots.network.message.MessagePlayerDataUpdate$MessageHolder.onMessage(MessagePlayerDataUpdate.java:52) ~[MessagePlayerDataUpdate$MessageHolder.class:?]
	at teamroots.roots.network.message.MessagePlayerDataUpdate$MessageHolder.onMessage(MessagePlayerDataUpdate.java:46) ~[MessagePlayerDataUpdate$MessageHolder.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.23.Final.jar:4.0.23.Final]` ...
you can see my complete fml log file: 
[fml-client-latest.log.txt](https://github.com/RootsTeam/Roots/files/838911/fml-client-latest.log.txt)

**Comment by kenijey** [comment]
and when i click confirm, it returns to the multiplayer server list.

**Comment by elucent** [comment]
I think I have a fix for this. Will release it on CurseForge soonish.

**Comment by kenijey** [comment]
ok

**Comment by elucent** [comment]
Tell me if this is fixed in 0.013.

**Comment by kenijey** [comment]
i think it is.
