### ISSUE TITLE
Game fails to load when I set this in config fairyPoolChance=0

### ISSUE THREAD

**Issue by PrinceOfAmber** [RootsTeam/Roots#223]
I was just trying o turn off some worldgen features in config.

Crash log 

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_25]
	at teamroots.roots.world.WorldGenFairyPool.generate(WorldGenFairyPool.java:55) ~[WorldGenFairyPool.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002) ~[auo.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982) ~[auo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158) ~[lv.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:174) ~[cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]

**Comment by Jomik** [comment]
Well, that seems to be because you've chosen a non-positive bound for the fairyPoolChance :) It has to be at least 1, I assume.
I think you need it to progress in the mod, in a way, so turning it off would be detrimental.
Though, if you can add a custom recipe for Fairy Dust, perhaps it should be something that can be turned off.

**Comment by elucent** [comment]
Should be fixed, I'll get a build out soonish.
