### ISSUE TITLE
1.11.2 Server Crash

### ISSUE THREAD

**Issue by Maitredetoi** [RootsTeam/Roots#227]
Crashes when Rose Thorns triggered by mob / player

5:21] [Server thread/WARN]: Skipping BlockEntity with id minecraft:forestry.swarm
[13:45:21] [Server thread/WARN]: Skipping Entity with id metamorph:morph
[13:45:21] [Server thread/WARN]: Skipping Entity with id animania:textures/entity/cows/cow_holstein.png
[13:45:21] [Server thread/WARN]: Skipping BlockEntity with id minecraft:tconstruct.craftingstation
[13:45:21] [Server thread/WARN]: Skipping Entity with id animania:textures/entity/cows/cow_friesian.png
[13:45:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
        at teamroots.roots.entity.EntityThornTrap.func_70071_h_(EntityThornTrap.java:117) ~[EntityThornTrap.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1965) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1748) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at teamroots.roots.entity.EntityThornTrap.func_70071_h_(EntityThornTrap.java:117) ~[EntityThornTrap.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1965) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1748) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2dca0d64 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257) ~[forge.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at teamroots.roots.entity.EntityThornTrap.func_70071_h_(EntityThornTrap.java:117) ~[EntityThornTrap.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1965) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1748) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Attempted to load class bou for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at teamroots.roots.entity.EntityThornTrap.func_70071_h_(EntityThornTrap.java:117) ~[EntityThornTrap.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1965) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1748) ~[ajs.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
        ... 4 more
[13:45:27] [Server thread/ERROR]: This crash report has been saved to: /home/timothy/MCServer/./crash-reports/crash-2017-06-14_13.45.27-server.txt
[13:45:27] [Server thread/INFO]: Stopping server
[13:45:27] [Server thread/INFO]: Saving players

**Comment by elucent** [comment]
Will be fixed in next release, and I'll build and release that tonight!
