### ISSUE TITLE
[MC 1.12.1 - roots-2-0.102] Crash :  thatch Rendering screen

### ISSUE THREAD

**Issue by MokuJinJin** [RootsTeam/Roots#253]
Inside herblore book, when i click on thatch cause MC to crash.

Forge : 14.22.1.2478
MC : 1.12.1

No other mods.

Full log : 

[22:19:08] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:43) ~[buv.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:242) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_175042_a(RenderItem.java:287) ~[bzw.class:?]
	at teamroots.roots.gui.GuiBook.renderItemStackAt(GuiBook.java:69) ~[GuiBook.class:?]
	at teamroots.roots.gui.GuiBook.func_73863_a(GuiBook.java:296) ~[GuiBook.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 17 more
[22:19:08] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 9/24/17 10:19 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:43)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:242)
	at net.minecraft.client.renderer.RenderItem.func_175042_a(RenderItem.java:287)
	at teamroots.roots.gui.GuiBook.renderItemStackAt(GuiBook.java:69)
	at teamroots.roots.gui.GuiBook.func_73863_a(GuiBook.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:43)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:242)
	at net.minecraft.client.renderer.RenderItem.func_175042_a(RenderItem.java:287)
	at teamroots.roots.gui.GuiBook.renderItemStackAt(GuiBook.java:69)
	at teamroots.roots.gui.GuiBook.func_73863_a(GuiBook.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

-- Screen render details --
Details:
	Screen name: teamroots.roots.gui.GuiBook
	Mouse location: Scaled: (192, 53). Absolute: (384, 373)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/353, l='MpServer', x=-195.50, y=68.00, z=256.50]]
	Chunk stats: MultiplayerChunkCache: 539, 539
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-200,64,252), Chunk: (at 8,4,12 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2317 game time, 2317 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityChicken['Chicken'/260, l='MpServer', x=-122.15, y=68.00, z=256.09], EntityChicken['Chicken'/261, l='MpServer', x=-124.10, y=68.00, z=264.77], EntitySkeleton['Skeleton'/262, l='MpServer', x=-119.69, y=25.00, z=334.47], EntityBat['Bat'/1798, l='MpServer', x=-178.25, y=52.68, z=281.60], EntityBat['Bat'/779, l='MpServer', x=-202.13, y=22.13, z=328.56], EntityBat['Bat'/780, l='MpServer', x=-199.69, y=23.06, z=313.98], EntitySkeleton['Skeleton'/1549, l='MpServer', x=-226.50, y=13.00, z=328.50], EntitySkeleton['Skeleton'/1049, l='MpServer', x=-260.50, y=18.00, z=197.50], EntityBat['Bat'/1842, l='MpServer', x=-223.66, y=27.96, z=333.58], EntityCow['Cow'/58, l='MpServer', x=-274.82, y=71.00, z=234.70], EntityBat['Bat'/1851, l='MpServer', x=-219.25, y=26.00, z=236.25], EntityBat['Bat'/1852, l='MpServer', x=-215.13, y=26.11, z=245.74], EntityZombie['Zombie'/1341, l='MpServer', x=-173.50, y=18.00, z=192.50], EntitySkeleton['Skeleton'/574, l='MpServer', x=-267.50, y=42.00, z=208.50], EntitySkeleton['Skeleton'/575, l='MpServer', x=-269.50, y=42.00, z=208.50], EntityBat['Bat'/1858, l='MpServer', x=-252.92, y=25.20, z=253.49], EntityCreeper['Creeper'/1605, l='MpServer', x=-198.50, y=17.00, z=207.50], EntityItem['item.tile.mushroom'/78, l='MpServer', x=-242.88, y=12.00, z=198.13], EntityItem['item.tile.mushroom'/88, l='MpServer', x=-237.05, y=12.00, z=196.82], EntityItem['item.tile.mushroom'/89, l='MpServer', x=-234.00, y=11.00, z=196.13], EntityPlayerSP['<PROFILE NAME>'/353, l='MpServer', x=-195.50, y=68.00, z=256.50], EntityCreeper['Creeper'/103, l='MpServer', x=-218.50, y=42.00, z=252.50], EntityZombie['Zombie'/104, l='MpServer', x=-210.50, y=35.00, z=253.50], EntityCow['Cow'/105, l='MpServer', x=-215.31, y=72.00, z=230.83], EntityBat['Bat'/106, l='MpServer', x=-199.07, y=24.08, z=318.85], EntityBat['Bat'/1649, l='MpServer', x=-211.63, y=22.81, z=226.75], EntityCow['Cow'/115, l='MpServer', x=-198.60, y=72.00, z=222.49], EntityCow['Cow'/116, l='MpServer', x=-197.69, y=72.00, z=222.49], EntityCow['Cow'/117, l='MpServer', x=-194.50, y=71.00, z=223.50], EntityBat['Bat'/1653, l='MpServer', x=-165.43, y=15.97, z=220.17], EntityCow['Cow'/118, l='MpServer', x=-195.59, y=72.00, z=219.82], EntityCow['Cow'/121, l='MpServer', x=-219.55, y=69.00, z=256.45], EntityCow['Cow'/122, l='MpServer', x=-206.19, y=71.00, z=236.53], EntityCow['Cow'/123, l='MpServer', x=-196.73, y=68.00, z=242.82], EntityCow['Cow'/125, l='MpServer', x=-207.50, y=70.00, z=286.19], EntityCow['Cow'/126, l='MpServer', x=-197.69, y=66.25, z=278.32], EntityEnderman['Enderman'/1406, l='MpServer', x=-249.50, y=40.00, z=219.50], EntityCow['Cow'/127, l='MpServer', x=-206.17, y=69.00, z=276.40], EntityZombie['Zombie'/1407, l='MpServer', x=-250.50, y=40.00, z=220.50], EntityItem['item.item.seeds'/128, l='MpServer', x=-200.08, y=68.00, z=275.20], EntityCreeper['Creeper'/1408, l='MpServer', x=-248.50, y=40.00, z=219.50], EntityItem['item.tile.flower1.dandelion'/129, l='MpServer', x=-201.88, y=66.00, z=278.47], EntityCreeper['Creeper'/1409, l='MpServer', x=-251.50, y=40.00, z=217.50], EntityItem['item.item.seeds'/130, l='MpServer', x=-199.91, y=66.00, z=277.38], EntityItem['item.item.seeds'/131, l='MpServer', x=-196.91, y=65.00, z=278.05], EntityItem['item.item.seeds'/132, l='MpServer', x=-197.91, y=65.00, z=279.10], EntityItem['item.item.seeds'/133, l='MpServer', x=-198.57, y=66.00, z=276.58], EntityItem['item.tile.flower1.dandelion'/134, l='MpServer', x=-198.52, y=66.00, z=277.09], EntityItem['item.tile.flower1.dandelion'/135, l='MpServer', x=-195.98, y=66.00, z=275.87], EntityItem['item.tile.flower1.dandelion'/136, l='MpServer', x=-194.29, y=65.00, z=277.67], EntityFairyCircle['entity.fairy_circle.name'/137, l='MpServer', x=-196.00, y=74.00, z=281.00], EntityItem['item.item.seeds'/138, l='MpServer', x=-192.89, y=65.00, z=283.29], EntityCreeper['Creeper'/1930, l='MpServer', x=-183.92, y=26.00, z=285.61], EntityItem['item.item.seeds'/139, l='MpServer', x=-192.76, y=65.00, z=279.46], EntityCreeper['Creeper'/1931, l='MpServer', x=-186.50, y=25.00, z=288.50], EntityItem['item.item.seeds'/140, l='MpServer', x=-196.90, y=67.00, z=288.13], EntityCreeper['Creeper'/1932, l='MpServer', x=-185.50, y=25.00, z=288.50], EntityZombie['Zombie'/1933, l='MpServer', x=-188.50, y=25.00, z=285.50], EntityBat['Bat'/1427, l='MpServer', x=-203.75, y=19.10, z=260.25], EntitySkeleton['Skeleton'/148, l='MpServer', x=-190.50, y=42.00, z=181.50], EntityCow['Cow'/149, l='MpServer', x=-190.50, y=71.00, z=190.50], EntityCow['Cow'/150, l='MpServer', x=-189.50, y=71.00, z=191.50], EntityCow['Cow'/151, l='MpServer', x=-188.50, y=71.00, z=189.50], EntityCreeper['Creeper'/152, l='MpServer', x=-183.50, y=18.00, z=205.50], EntityCow['Cow'/154, l='MpServer', x=-187.50, y=70.00, z=192.50], EntityZombie['Zombie'/1692, l='MpServer', x=-227.50, y=43.00, z=221.50], EntityCow['Cow'/158, l='MpServer', x=-190.23, y=70.00, z=288.48], EntityItem['item.item.seeds'/159, l='MpServer', x=-189.65, y=66.00, z=279.49], EntitySkeleton['Skeleton'/1442, l='MpServer', x=-201.50, y=21.00, z=244.50], EntitySkeleton['Skeleton'/1444, l='MpServer', x=-206.50, y=30.00, z=215.50], EntityZombie['Zombie'/1700, l='MpServer', x=-270.50, y=23.00, z=272.50], EntitySkeleton['Skeleton'/1445, l='MpServer', x=-207.50, y=30.00, z=215.50], EntityZombie['Zombie'/1701, l='MpServer', x=-271.27, y=23.00, z=274.50], EntityCreeper['Creeper'/683, l='MpServer', x=-258.50, y=37.00, z=250.50], EntityZombie['Zombie'/1461, l='MpServer', x=-231.50, y=20.00, z=234.50], EntitySkeleton['Skeleton'/1462, l='MpServer', x=-176.50, y=43.00, z=287.31], EntityBat['Bat'/1720, l='MpServer', x=-194.15, y=16.02, z=211.70], EntityZombie['Zombie'/1220, l='MpServer', x=-200.50, y=34.00, z=242.50], EntityBat['Bat'/202, l='MpServer', x=-156.02, y=20.10, z=219.05], EntityItem['item.item.seeds'/458, l='MpServer', x=-161.68, y=62.00, z=284.16], EntityBat['Bat'/1998, l='MpServer', x=-202.70, y=39.07, z=193.99], EntityZombie['Zombie'/207, l='MpServer', x=-142.49, y=14.00, z=282.20], EntityBat['Bat'/1999, l='MpServer', x=-200.09, y=39.07, z=194.91], EntityItem['item.tile.rail'/208, l='MpServer', x=-156.98, y=41.00, z=319.13], EntityItem['item.tile.rail'/211, l='MpServer', x=-158.65, y=41.00, z=319.77], EntitySquid['Squid'/2003, l='MpServer', x=-152.30, y=60.00, z=312.60], EntityItem['item.tile.rail'/212, l='MpServer', x=-156.13, y=41.00, z=319.79], EntitySquid['Squid'/2004, l='MpServer', x=-153.05, y=61.00, z=310.88], EntityZombie['Zombie'/1749, l='MpServer', x=-172.50, y=52.00, z=253.50], EntityEnderman['Enderman'/1494, l='MpServer', x=-163.50, y=20.00, z=277.50], EntitySkeleton['Skeleton'/1750, l='MpServer', x=-171.50, y=52.00, z=250.50], EntitySkeleton['Skeleton'/986, l='MpServer', x=-160.50, y=46.00, z=206.50], EntityCreeper['Creeper'/1499, l='MpServer', x=-165.50, y=16.00, z=217.50], EntitySpider['Spider'/2013, l='MpServer', x=-204.50, y=33.00, z=245.50], EntityZombie['Zombie'/2015, l='MpServer', x=-207.50, y=33.00, z=246.50], EntityZombie['Zombie'/1760, l='MpServer', x=-201.49, y=28.00, z=314.20], EntityZombie['Zombie'/1761, l='MpServer', x=-198.31, y=28.00, z=311.54], EntityZombie['Zombie'/1762, l='MpServer', x=-196.50, y=28.00, z=310.50], EntitySpider['Spider'/1764, l='MpServer', x=-199.39, y=28.00, z=311.22], EntityCreeper['Creeper'/1511, l='MpServer', x=-269.50, y=26.00, z=239.50], EntityCreeper['Creeper'/1512, l='MpServer', x=-269.50, y=26.00, z=239.50], EntityCreeper['Creeper'/1513, l='MpServer', x=-266.78, y=25.00, z=244.42], EntitySprout['Sprout'/234, l='MpServer', x=-141.50, y=65.94, z=201.50], EntitySkeleton['Skeleton'/2026, l='MpServer', x=-206.50, y=33.00, z=242.50], EntitySprout['Sprout'/236, l='MpServer', x=-141.50, y=64.94, z=196.50], EntityChicken['Chicken'/239, l='MpServer', x=-130.50, y=70.00, z=258.50], EntityChicken['Chicken'/240, l='MpServer', x=-128.50, y=70.00, z=259.50], EntityMinecartChest['Minecart with Chest'/243, l='MpServer', x=-138.50, y=41.06, z=318.50], EntityItem['item.tile.torch'/244, l='MpServer', x=-134.13, y=41.00, z=316.95], EntityEnderman['Enderman'/1268, l='MpServer', x=-165.50, y=22.00, z=257.50], EntityItem['item.tile.torch'/245, l='MpServer', x=-133.36, y=40.00, z=312.48], EntitySkeleton['Skeleton'/1269, l='MpServer', x=-165.50, y=22.00, z=257.50], EntityBat['Bat'/1781, l='MpServer', x=-158.74, y=18.10, z=218.40], EntityCreeper['Creeper'/503, l='MpServer', x=-206.50, y=47.00, z=285.50], EntityBat['Bat'/1787, l='MpServer', x=-154.61, y=23.72, z=255.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264410392 bytes (252 MB) / 727187456 bytes (693 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.41 Powered by Forge 14.22.1.2478 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                                  | Signature                                |
	|:--------- |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.1       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp       | 9.19         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.1-14.22.1.2478-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.22.1.2478 | forge-1.12.1-14.22.1.2478-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | roots     | 0.102        | roots-2-0.102.jar                       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz

**Comment by elucent** [comment]
Update your game before posting a crash report.

**Comment by MokuJinJin** [comment]
Sorry i've download it before 0.103 has been posted.
It's been a week, i can't check every day if every mod has been updated.

My mistake, it has been fixed in 0.103.
