### ISSUE TITLE
[1.10.2] [Bug] Bug in event manager

### ISSUE THREAD

**Issue by Dijkstra1** [RootsTeam/Roots#88]
My sister mad the staff that summons skeletons to fight for you, and yes a skeleton appeared, then did nothing, then took damage and diapered followed, mobs freezing and then server disconecting us. When I check server console it kept repeated this  
```
[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:486) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:173) ~[sg.class:?]
	at elucent.roots.EventManager.onLivingTarget(EventManager.java:149) ~[EventManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_447_EventManager_onLivingTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~
```

Full log: [Log](https://gist.githubusercontent.com/Dijkstra1/b580f32bcdf8eb6aaf3504e38917ed16/raw/bcee85b0a46d70ccda7d05fa10abc62b5c539ef2/Root%2520bug.txt) (Well not full log the server had been running for a about week it from just before the issues started utill I forced the server close

Edit:
Minecraft Version: 1.10.2
Forge Version: 1.10.2-12.18.1.2026
Roots Version: 1.10.2-0.110.0
ModPack: [All the mods](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods#t1:description)
ModPack Version: 1.10.2 v1.6-Hotfix (Date of bug)

**Comment by elucent** [comment]
That spell is just buggy in general. I'll replace it with something new in the next update.

**Comment by elucent** [comment]
Whoops, didn't mean to close the issue. :P

**Comment by elucent** [comment]
This spell has been reworked completely. I hope you enjoy the new one!
